name: roz
channels:
  - default
dependencies:
  - python>=3.8,<3.10
  - numpy>=1.21
  - matplotlib>=3.4
  - pytest>=6.2
  - tqdm
  - beautifulsoup4
  - scipy
  # Astropy Channel
  - astropy::astropy
  - astropy::ccdproc
  - astropy::photutils
  # Conda-Forge Channel
  - conda-forge::atlassian-python-api
  - conda-forge::ffmpeg-python
  - conda-forge::setuptools>=59.7
  - conda-forge::setuptools_scm
  - conda-forge::black
  - conda-forge::pylint
  # Via pip
  - pip
  - pip:
    - git+https://github.com/LowellObservatory/ligmos
    - git+https://github.com/LowellObservatory/JohnnyFive
