name: roz
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pyyaml>=5.4
  - requests>=2.26
  - packaging>=21.0
  - numpy>=1.21
  - scipy>=1.7
  - astropy>=4.3
  - setuptools>=46.4
  - setuptools_scm
  - matplotlib>=3.4
  - pytest>=6.2
  - pip
  - importlib_resources
  - tqdm
  - atlassian-python-api
  - beautifulsoup4
  - ccdproc
  - google-api-python-client
  - google-auth-httplib2
  - google-auth-oauthlib
